/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (5.3.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.example.api;

import org.example.model.InlineObject;
import io.swagger.annotations.*;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2023-02-12T18:16:53.877393400+01:00[Europe/Warsaw]")
@Validated
@Api(value = "sportservice", description = "the sportservice API")
public interface SportserviceApi {

    /**
     * POST /sportservice/events : Add events to database
     *
     * @param inlineObject  (required)
     * @return created successfully (status code 201)
     *         or creation unsucceful (status code 400)
     */
    @ApiOperation(value = "Add events to database", nickname = "addEvents", notes = "", tags={ "event-controller", })
    @ApiResponses(value = { 
        @ApiResponse(code = 201, message = "created successfully"),
        @ApiResponse(code = 400, message = "creation unsucceful") })
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/sportservice/events",
        consumes = { "application/json" }
    )
    ResponseEntity<Void> addEvents(@ApiParam(value = "", required = true) @Valid @RequestBody InlineObject inlineObject);


    /**
     * GET /sportservice/events : List events by given parameters
     *
     * @return A PDF file (status code 200)
     */
    @ApiOperation(value = "List events by given parameters", nickname = "getEvents", notes = "", response = String.class, tags={ "event-controller", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "A PDF file", response = String.class) })
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/sportservice/events",
        produces = { "text/plain" }
    )
    ResponseEntity<String> getEvents();

}
